main: org.crayne.ptjdnc.NameColorPlugin
name: PlaytimeJoindateNameColor
version: @VERSION@
description: @DESCRIPTION@
api-version: 1.20
authors: [ crayne, bierdosenhalter ]
depend: [ DonationAPI ]
folia-supported: true

commands:
  namecolor:
    description: "main namecolor command"
    aliases: ["nc"]
  itemcolor:
    description: "itemcolor command"
    aliases: ["ic"]
  opnamecolor:
    description: "namecolor command for ops to change other players nc"
    aliases: ["opnc"]